# Generated by Django 5.1 on 2025-02-20 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FloorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GynecologicalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MastitisStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UdderHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('telephone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +251912345678 or 0912345678).', regex='^\\+?1?\\d{9,15}$')])),
                ('location_gps', models.CharField(blank=True, max_length=255, null=True)),
                ('fertility_camp_no', models.PositiveIntegerField(help_text='Number of fertility camps')),
                ('total_number_of_cows', models.PositiveIntegerField()),
                ('number_of_calves', models.PositiveIntegerField()),
                ('number_of_milking_cow', models.PositiveIntegerField()),
                ('total_daily_milk', models.PositiveIntegerField(help_text='Total daily milk production in liters')),
                ('main_feed', models.TextField()),
                ('farm_hygiene_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('rate_of_cow_feeding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms_feeding', to='FarmManager.feedingfrequency')),
                ('rate_of_water_giving', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms_watering', to='FarmManager.feedingfrequency')),
                ('type_of_floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='FarmManager.floortype')),
                ('type_of_housing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='FarmManager.housingtype')),
                ('source_of_water', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='FarmManager.watersource')),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=50)),
                ('age_in_days', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('parity', models.PositiveIntegerField(default=0, help_text='Number of times the cow has given birth')),
                ('body_weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('bcs', models.DecimalField(choices=[(1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')], decimal_places=1, max_digits=2, verbose_name='Body Condition Score')),
                ('lactation_number', models.PositiveIntegerField(default=0)),
                ('days_in_milk', models.PositiveIntegerField(default=0)),
                ('average_daily_milk', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('cow_inseminated_before', models.BooleanField(default=False)),
                ('last_date_insemination', models.DateField(blank=True, null=True)),
                ('number_of_inseminations', models.PositiveIntegerField(default=0)),
                ('id_or_breed_bull_used', models.CharField(blank=True, max_length=100)),
                ('last_calving_date', models.DateField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='FarmManager.breedtype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='FarmManager.farm')),
                ('gynecological_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='FarmManager.gynecologicalstatus')),
            ],
            options={
                'ordering': ['farm', 'cow_id'],
                'unique_together': {('farm', 'cow_id')},
            },
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cow_pregnant', models.BooleanField(default=False)),
                ('heat_sign_start', models.DateTimeField()),
                ('heat_sign_end', models.DateTimeField(blank=True, null=True)),
                ('heat_signs_seen', models.TextField(blank=True)),
                ('pregnancy_date', models.DateField(blank=True, null=True)),
                ('calving_date', models.DateField(blank=True, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_records', to='FarmManager.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_records', to='FarmManager.farm')),
            ],
            options={
                'verbose_name_plural': 'Reproduction Records',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproductive_health', models.TextField(blank=True)),
                ('metabolic_health', models.TextField(blank=True)),
                ('is_cow_vaccinated', models.BooleanField(default=False)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('vaccination_type', models.TextField(blank=True)),
                ('has_cow_taken_deworming', models.BooleanField(default=False)),
                ('deworming_date', models.DateField(blank=True, null=True)),
                ('deworming_type', models.TextField(blank=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='FarmManager.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='FarmManager.farm')),
                ('general_health', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='FarmManager.generalhealthstatus')),
                ('mastitis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='FarmManager.mastitisstatus')),
                ('udder_health', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='FarmManager.udderhealthstatus')),
            ],
            options={
                'verbose_name_plural': 'Health Records',
            },
        ),
    ]
