# Generated by Django 5.1 on 2025-01-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('telephone_number', models.CharField(max_length=15)),
                ('location_gps', models.CharField(blank=True, max_length=255, null=True)),
                ('fertility_camp_no', models.IntegerField()),
                ('total_number_of_cows', models.IntegerField()),
                ('number_of_calves', models.IntegerField()),
                ('number_of_calf', models.IntegerField()),
                ('number_of_milking_cow', models.IntegerField()),
                ('total_daily_milk', models.IntegerField()),
                ('type_of_housing', models.CharField(choices=[('free stall', 'Free Stall'), ('tie stall', 'Tie Stall'), ('traditional', 'Traditional')], max_length=50)),
                ('type_of_floor', models.CharField(choices=[('concrete', 'Concrete'), ('stone', 'Stone'), ('soil', 'Soil'), ('mat', 'Mat')], max_length=50)),
                ('main_feed', models.TextField()),
                ('rate_of_cow_feeding', models.CharField(choices=[('once', 'Once'), ('twice', 'Twice'), ('three times', 'Three Times')], max_length=50)),
                ('source_of_water', models.CharField(choices=[('tap', 'Tap'), ('wells', 'Wells')], max_length=50)),
                ('rate_of_water_giving', models.CharField(choices=[('once', 'Once'), ('twice', 'Twice'), ('three times', 'Three Times')], max_length=50)),
                ('farm_hygiene_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('cow_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=100)),
                ('age_in_days', models.IntegerField()),
                ('sex', models.CharField(default='milking_cow', max_length=50)),
                ('parity', models.IntegerField()),
                ('body_weight', models.FloatField()),
                ('bcs', models.FloatField(choices=[(1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')])),
                ('gynecological_status', models.CharField(choices=[('Estrus', 'Estrus'), ('AI', 'AI'), ('Pregna', 'Pregna')], max_length=50)),
                ('lactation_number', models.IntegerField()),
                ('days_in_milk', models.IntegerField()),
                ('average_daily_milk', models.FloatField()),
                ('cow_inseminated_before', models.BooleanField()),
                ('last_date_insemination', models.DateField()),
                ('number_of_inseminations', models.IntegerField()),
                ('id_or_breed_bull_used', models.IntegerField()),
                ('last_calving_date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmManager.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udder_health', models.CharField(choices=[('4qt', '4 Quarters'), ('3qt', '3 Quarters'), ('2qt', '2 Quarters'), ('1qt', '1 Quarter')], max_length=50)),
                ('mastitis', models.CharField(choices=[('negative', 'Negative'), ('clinical mastitis', 'Clinical Mastitis')], max_length=50)),
                ('general_health', models.CharField(choices=[('normal', 'Normal'), ('sick', 'Sick')], max_length=50)),
                ('reproductive_health', models.TextField()),
                ('metabolic_health', models.TextField()),
                ('is_cow_vaccinated', models.BooleanField()),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('vaccination_type', models.TextField()),
                ('has_cow_taken_deworming', models.BooleanField()),
                ('deworming_date', models.DateField(blank=True, null=True)),
                ('deworming_type', models.TextField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmManager.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cow_pregnant', models.BooleanField()),
                ('heat_sign_start', models.DateTimeField()),
                ('heat_sign_end', models.DateTimeField(blank=True, null=True)),
                ('heat_signs_seen', models.TextField()),
                ('pregnancy_date', models.DateField()),
                ('calving_date', models.DateField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmManager.cow')),
            ],
        ),
    ]
