# Generated by Django 5.2 on 2025-12-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0008_add_cluster_number_to_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="inseminationrecord",
            name="insemination_date",
            field=models.DateField(
                blank=True,
                help_text="Actual date when insemination was performed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inseminationrecord",
            name="recorded_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date when this record was created in the system",
            ),
        ),
    ]
