# Generated by Django 5.1 on 2024-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_animal_fertility_window_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='dmy',
            new_name='average_daily_milk',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='dalc',
            new_name='days_after_calving',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='dim',
            new_name='insemination_number',
        ),
        migrations.AddField(
            model_name='animal',
            name='date_ai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='no_days_in_milk',
            field=models.IntegerField(default=0),
        ),
    ]
